import WOQLTableConfig = require("./tableConfig");
import WOQLChartConfig = require("./chartConfig");
import WOQLGraphConfig = require("./graphConfig");
import WOQLChooserConfig = require("./chooserConfig");
import WOQLStreamConfig = require("./streamConfig");
import FrameConfig = require("./frameConfig");
import WOQLRule = require("./woqlRule");
import FrameRule = require("./frameRule");
export function table(): WOQLTableConfig;
export function chart(): WOQLChartConfig;
export function graph(): WOQLGraphConfig;
export function chooser(): WOQLChooserConfig;
export function stream(): WOQLStreamConfig;
export function document(): FrameConfig;
export function loadConfig(config: any): WOQLTableConfig;
export function rule(type: any): WOQLRule | FrameRule;
export function pattern(type: any): WOQLRule.WOQLPattern | FrameRule.FramePattern;
export function matchRow(rules: any, row: any, rownum: any, action: any): any[];
export function matchColumn(rules: any, key: any, action: any): any[];
export function matchCell(rules: any, row: any, key: any, rownum: any, action: any): any[];
export function matchNode(rules: any, row: any, key: any, nid: any, action: any): any[];
export function matchEdge(rules: any, row: any, keya: any, keyb: any, action: any): any[];
export function matchFrame(rules: any, frame: any, onmatch: any): FrameRule[];
