module.exports = {
				 WOQLClient:require('./lib/woqlClient'),
                 ConnectionCapabilities:require('./lib/connectionCapabilities'),
                 ConnectionConfig:require('./lib/connectionConfig'),
                 IDParser:require('./lib/terminusIDParser'),
                 ErrorMessage:require('./lib/errorMessage'),
                 UTILS:require('./lib/utils'),
                 WOQLResult:require('./lib/woqlResult'),
                 WOQLRule:require('./lib/woqlRule'),
                 FrameRule:require('./lib/frameRule'),
                 View:require('./lib/woqlView'),
                 DocumentFrame:require('./lib/viewer/documentFrame'),
                 WOQLGraph:require('./lib/viewer/woqlGraph'),
                 WOQLTable:require('./lib/viewer/woqlTable'),
                 WOQLChooser:require('./lib/viewer/woqlChooser'),
                 WOQLChart:require('./lib/viewer/woqlChart'),
                 WOQLStream:require('./lib/viewer/woqlStream'),
                 WOQL:require('./lib/woql')};